# Site settings
title: "My Resume"
#description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sobhit Kumar"
resume_title:                   "Android Application Developer"
resume_contact_email:           "sobhit2010@gmail.com"
#resume_contact_telephone:       "09891450298"
resume_contact_address:         "2160/13, Badarpur Border, New Delhi"
resume_header_contact_info: "H.No-2160/13, 3rd 60 feet Road, MolarBand Extn, Badarpur Border, New Delhi | 110044| sobhit2010@gmail.com"
resume_header_intro: "<p>I am a B.tech Graduate in mechanical and Automation engg. 
From Guru Gobind Singh Indraprastha University, New Delhi. I have completed my graduation
 in year 2015. After trying for government exams for one and a half year , having no luck
  there I stated to learn coding . From around last 10 month I have been study and coding 
  in android . I have design, coded and published some android apps in play store by myself, also
  some of projects repos are available on Github. Actively looking for Job.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "Yes"

# Decide which sections to use
# comment out to hide

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/MrDroid17"
  resume_linkedin_url:          "https://www.linkedin.com/in/sobhit-kumar/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
